### ISSUE TITLE
Suddenly error is showing

### ISSUE THREAD

**Issue by maruf1506** [wolfdevsllc/og-image-overlay#10]
![Screenshot 2024-06-20 232944](https://github.com/wolfdevsllc/og-image-overlay/assets/45971229/794b8997-7b14-4cac-8162-556f7bd6b677)
i successfully setup and long time i use this plugin but suddenly plugin is not working. This error is showing. black screen or broken image showing instead Image
Advanced Thanks..

**Comment by itsmereal** [comment]
Hi, I will need details of the issue. Can you please share your website URL so I can check?

**Comment by maruf1506** [comment]
sorry for late reply i use custom url this is my url [https://www.ekotarkantho.com/ogio/15401/](url) when i try to laod image then broken image is shown.

**Comment by maruf1506** [comment]
Problem fixed. Thanks for response.
