### ISSUE TITLE
Different Featured image - Different social image from yoast seo

### ISSUE THREAD

**Issue by sokmakaroni** [wolfdevsllc/og-image-overlay#9]
Hello . i am using your plugin but i have this issue. In my wordpress page in articles i have featured images of 700x700. I added the yoast seo plugin and i am using it to upload a different social image with the correct dimensions. But the plugin isnt working correct with that. I am getting an overlay image of the featured image and not of the social image . is there any way to make it work with the social image? thank you very very much.

**Comment by itsmereal** [comment]
In the next update (should be available today), we added option to use Yoast Social Image (Facebook or X) as source image for the open graph image. Meanwhile, we are working on something more awesome. Will update our plugin users about it when available. Thanks

**Comment by sokmakaroni** [comment]
thats amazing.thank you very much.
